<img src="https://filoger.com/wp-content/uploads/2021/09/circle-logo-1536x1536.png" alt="keras" width="150" height="150">
<h1 align=center><font size = 7>Lab 02 : NumPy</font></h1>
<h1 align=center><font size = 4>Filoger Summer School, 1401 | DeadLine: 15th Tir, 23:00 </font></h1>



## Question Sheet!

<div class="alert alert-block alert-info" style="margin-top: 20px">
<font size = 3>

<b>Download the Question sheet from the following link!</b>
-   <a href="https://new.edmodo.com/groups/filoger-summer-school-38664125">Lab 02: Question sheet: NumPy</a>
</font>
</div>


## Table of Exercises!

01. [Question 01](#question01)
2. [Question 02](#question02).
3. [Question 03](#question03).
4. [Question 04](#question04).
5. [Question 05](#question05).
6. [Question 06](#question06).
7. [Question 07](#question07).
8. [Question 08](#question08).
9. [Question 09](#question09).



<a id='item312'></a>


<a id='question01'></a>
## Question 01




In [1]:
#Leave the answer of question 01 here!
import numpy as np
array = np.zeros((1,6))
array

array([[0., 0., 0., 0., 0., 0.]])

<a id='question02'></a>
## Question 02




In [2]:
#Leave the answer of question 02 here!
array = np.ones((3,5))
array

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

<a id='question03'></a>
## Question 03




In [3]:
#Leave the answer of question 03 here!
array = np.arange(20,61,1)
array

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59, 60])

<a id='question04'></a>
## Question 04




In [4]:
#Leave the answer of question 04 here!
array = np.arange(15,56,2)
array

array([15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47,
       49, 51, 53, 55])

<a id='question05'></a>
## Question 05




In [5]:
#Leave the answer of question 05 here!
array = np.random.uniform(0,1,15)
array

array([0.24210709, 0.82878528, 0.14508555, 0.71837093, 0.016365  ,
       0.68160448, 0.73659661, 0.82361323, 0.55237146, 0.2055469 ,
       0.23309302, 0.08729762, 0.11246134, 0.69658475, 0.89575708])

<a id='question06'></a>
## Question 06




In [6]:
#Leave the answer of question 06 here!
array = np.eye(4)
array

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

<a id='question07'></a>
## Question 07




In [7]:
#Leave the answer of question 07 here!
array = np.random.normal(0,1,(3,5))
array

array([[ 0.77110364,  0.88811515, -1.25075096,  0.79941964,  0.16442984],
       [-1.02619835, -0.5829669 ,  0.25577078,  0.91854224, -0.88323955],
       [-0.02635117,  1.01300985, -0.86189271, -0.4966644 , -0.07254705]])

<a id='question08'></a>
## Question 08




In [8]:
#Leave the answer of question 08 here!
array = np.linspace(0,1,13)
array

array([0.        , 0.08333333, 0.16666667, 0.25      , 0.33333333,
       0.41666667, 0.5       , 0.58333333, 0.66666667, 0.75      ,
       0.83333333, 0.91666667, 1.        ])

<a id='question09'></a>
## Question 09




In [9]:
#Leave the answer of question 09 here!
array = np.random.normal(6,4,(6,4))
array


array([[-0.36279233,  6.78665293,  6.35775352,  6.59901883],
       [ 7.3104456 ,  1.84757784, -1.38817254, 11.7401229 ],
       [ 7.63525037,  0.88716318, 10.72833666,  6.24506347],
       [ 6.00949421,  7.16863452,  8.39204035,  8.10018087],
       [ 7.31398974,  7.90451224,  6.47223911,  6.57837682],
       [ 3.68286095,  4.74324852,  4.34553801,  6.59317197]])

## Best Wishes!, Filoger


